### ISSUE TITLE
Something wrong on mobile

### ISSUE THREAD

**Issue by SirGordon** [TheYellowThorn/sandcastle#4]
I have exported a project from SandCastle with some simple hills, removed code related to water and it's running good on PC. But when i try it on my androids, i get 2-3 fps on phone and 15 on tablet. Is something wrong with **[the code](https://gist.github.com/SirGordon/e843a1175bb7eaf471ad)**? (changed my directories to "<my user directory>" and "<my project directory>")

Also splats are blending wrong / different from what i see on PC.

Phone: Galaxy Nexus Android 4.1.1
Tablet: Nexus 7 Android 5.1.1

AIR17
Contex3DProfile baseline

**Comment by TheYellowThorn** [comment]
@SirGordon If you could start redirecting customer service questions to www.theyellowthorn.com/reporting, that would be very helpful.  That also provides you a way to submit a screenshot so that we can look at your blending issue.

At first glance, I see a few things which could be addressed with how you have set up your code:

[SWF(frameRate="60")]
60fps is pretty high for an older phone and tablet.  Placing a higher frame rate can sometimes actually lower your overall frame rate because you are trying to force the machine to update code every time a new frame has been entered.  For mobile and tablets, I would drop this down to between 24 to 30 frames per second.

public var LODDistances : Vector.<Number> = Vector.<Number>([51200, 25600, 15360, 1920, 640, 256]);
You may be running into a polygon count problem.  I would adjust your LODs so that you don't even use the highest two for older phones and tablets.  For instance, try changing them to something like this:
public var LODDistances : Vector.<Number> = Vector.<Number>([15360, 1920, 640, 256, 0, 0]);  You have to be sensitive to the hardware limits on your devices.  Keep playing around with these settings until you get your app to a sweet spot.

One last performance thing:  I would upload your own splat textures at the size of 256x256 or smaller and see if that improves your performance.  You can always increase the tiling on the materials to keep things still looking nice.  It seems the GPUs on your devices are not very powerful, and this may help take some of the load off of them.

For the blending issue, make sure you have set the variables in your XML file as they appear below.
<renderMode>direct</renderMode>
<depthAndStencil>true</depthAndStencil>

**Comment by SirGordon** [comment]
you mean <renderMode>direct</renderMode> and <\depthAndStencil>true</depthAndStencil>, I'm sure their values are correcet, because the same code and the same AIR descriptor works as expected on the PC. Thanks for the answer, I'll try to play with settings.
And submit a screenshot from the mobile devices to the reporting service.

**Comment by TheYellowThorn** [comment]
Yes, except for the first backslash.  There should not be a backslash before the opening depthAndStencil tag.
